// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetRequest struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Email               string             `json:"email"`
	OtpHash             string             `json:"otp_hash"`
	ResetTokenHash      pgtype.Text        `json:"reset_token_hash"`
	Attempts            int32              `json:"attempts"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ResetTokenExpiresAt pgtype.Timestamptz `json:"reset_token_expires_at"`
	UsedAt              pgtype.Timestamptz `json:"used_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Key         string             `json:"key"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type RolePermission struct {
	RoleKey       string `json:"role_key"`
	PermissionKey string `json:"permission_key"`
	Effect        string `json:"effect"`
}

type UserPermissionOverride struct {
	UserID        pgtype.UUID        `json:"user_id"`
	PermissionKey string             `json:"permission_key"`
	Effect        string             `json:"effect"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
