// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetRequest = `-- name: CreatePasswordResetRequest :exec
INSERT INTO password_reset_requests (
  id,
  user_id,
  email,
  otp_hash,
  reset_token_hash,
  attempts,
  expires_at,
  reset_token_expires_at,
  used_at,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreatePasswordResetRequestParams struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Email               string             `json:"email"`
	OtpHash             string             `json:"otp_hash"`
	ResetTokenHash      pgtype.Text        `json:"reset_token_hash"`
	Attempts            int32              `json:"attempts"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ResetTokenExpiresAt pgtype.Timestamptz `json:"reset_token_expires_at"`
	UsedAt              pgtype.Timestamptz `json:"used_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePasswordResetRequest(ctx context.Context, arg CreatePasswordResetRequestParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetRequest,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.OtpHash,
		arg.ResetTokenHash,
		arg.Attempts,
		arg.ExpiresAt,
		arg.ResetTokenExpiresAt,
		arg.UsedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPasswordResetByResetTokenHash = `-- name: GetPasswordResetByResetTokenHash :one
SELECT
  id,
  user_id,
  email,
  otp_hash,
  reset_token_hash,
  attempts,
  expires_at,
  reset_token_expires_at,
  used_at,
  created_at,
  updated_at
FROM password_reset_requests
WHERE reset_token_hash = $1
  AND used_at IS NULL
  AND reset_token_expires_at > $2
LIMIT 1
`

type GetPasswordResetByResetTokenHashParams struct {
	ResetTokenHash      pgtype.Text        `json:"reset_token_hash"`
	ResetTokenExpiresAt pgtype.Timestamptz `json:"reset_token_expires_at"`
}

func (q *Queries) GetPasswordResetByResetTokenHash(ctx context.Context, arg GetPasswordResetByResetTokenHashParams) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByResetTokenHash, arg.ResetTokenHash, arg.ResetTokenExpiresAt)
	var i PasswordResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.OtpHash,
		&i.ResetTokenHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ResetTokenExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementPasswordResetAttempts = `-- name: IncrementPasswordResetAttempts :exec
UPDATE password_reset_requests
SET
  attempts = attempts + 1,
  updated_at = $1
WHERE id = $2
`

type IncrementPasswordResetAttemptsParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) IncrementPasswordResetAttempts(ctx context.Context, arg IncrementPasswordResetAttemptsParams) error {
	_, err := q.db.Exec(ctx, incrementPasswordResetAttempts, arg.UpdatedAt, arg.ID)
	return err
}

const latestActivePasswordResetByEmail = `-- name: LatestActivePasswordResetByEmail :one
SELECT
  id,
  user_id,
  email,
  otp_hash,
  reset_token_hash,
  attempts,
  expires_at,
  reset_token_expires_at,
  used_at,
  created_at,
  updated_at
FROM password_reset_requests
WHERE email = $1
  AND used_at IS NULL
  AND expires_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type LatestActivePasswordResetByEmailParams struct {
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) LatestActivePasswordResetByEmail(ctx context.Context, arg LatestActivePasswordResetByEmailParams) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, latestActivePasswordResetByEmail, arg.Email, arg.ExpiresAt)
	var i PasswordResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.OtpHash,
		&i.ResetTokenHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ResetTokenExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :execrows
UPDATE password_reset_requests
SET
  used_at = $1,
  updated_at = $1
WHERE id = $2
  AND used_at IS NULL
`

type MarkPasswordResetUsedParams struct {
	UsedAt pgtype.Timestamptz `json:"used_at"`
	ID     pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, arg MarkPasswordResetUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordResetUsed, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :execrows
UPDATE password_reset_requests
SET
  reset_token_hash = $1,
  reset_token_expires_at = $2,
  updated_at = $3
WHERE id = $4
  AND used_at IS NULL
`

type SetPasswordResetTokenParams struct {
	ResetTokenHash      pgtype.Text        `json:"reset_token_hash"`
	ResetTokenExpiresAt pgtype.Timestamptz `json:"reset_token_expires_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ID                  pgtype.UUID        `json:"id"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPasswordResetToken,
		arg.ResetTokenHash,
		arg.ResetTokenExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
