// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPermissions = `-- name: ListPermissions :many
SELECT
  id,
  key,
  description,
  created_at,
  updated_at,
  deleted_at
FROM permissions
WHERE deleted_at IS NULL
ORDER BY key ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionEffects = `-- name: ListRolePermissionEffects :many
SELECT
  permission_key,
  effect
FROM role_permissions
WHERE role_key = $1
`

type ListRolePermissionEffectsRow struct {
	PermissionKey string `json:"permission_key"`
	Effect        string `json:"effect"`
}

func (q *Queries) ListRolePermissionEffects(ctx context.Context, roleKey string) ([]ListRolePermissionEffectsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissionEffects, roleKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePermissionEffectsRow{}
	for rows.Next() {
		var i ListRolePermissionEffectsRow
		if err := rows.Scan(&i.PermissionKey, &i.Effect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionOverrideEffects = `-- name: ListUserPermissionOverrideEffects :many
SELECT
  permission_key,
  effect
FROM user_permission_overrides
WHERE user_id = $1
`

type ListUserPermissionOverrideEffectsRow struct {
	PermissionKey string `json:"permission_key"`
	Effect        string `json:"effect"`
}

func (q *Queries) ListUserPermissionOverrideEffects(ctx context.Context, userID pgtype.UUID) ([]ListUserPermissionOverrideEffectsRow, error) {
	rows, err := q.db.Query(ctx, listUserPermissionOverrideEffects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPermissionOverrideEffectsRow{}
	for rows.Next() {
		var i ListUserPermissionOverrideEffectsRow
		if err := rows.Scan(&i.PermissionKey, &i.Effect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
