// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO auth_sessions (
  id,
  user_id,
  refresh_jti,
  revoked_at,
  expires_at,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $6)
`

type CreateSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshJti,
		arg.RevokedAt,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  id,
  user_id,
  refresh_jti,
  revoked_at,
  expires_at,
  created_at
FROM auth_sessions
WHERE id = $1
`

type GetSessionByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RefreshJti pgtype.UUID        `json:"refresh_jti"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshJti,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
SET
  revoked_at = COALESCE(revoked_at, $1),
  updated_at = $1
WHERE id = $2
`

type RevokeSessionParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.UpdatedAt, arg.ID)
	return err
}

const revokeSessionsByUserID = `-- name: RevokeSessionsByUserID :exec
UPDATE auth_sessions
SET
  revoked_at = COALESCE(revoked_at, $1),
  updated_at = $1
WHERE user_id = $2
  AND revoked_at IS NULL
`

type RevokeSessionsByUserIDParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) RevokeSessionsByUserID(ctx context.Context, arg RevokeSessionsByUserIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUserID, arg.UpdatedAt, arg.UserID)
	return err
}

const rotateSessionRefresh = `-- name: RotateSessionRefresh :execrows
UPDATE auth_sessions
SET
  refresh_jti = $1,
  expires_at = $2,
  updated_at = $3
WHERE id = $4
  AND refresh_jti = $5
  AND revoked_at IS NULL
  AND expires_at > $3
`

type RotateSessionRefreshParams struct {
	RefreshJti   pgtype.UUID        `json:"refresh_jti"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ID           pgtype.UUID        `json:"id"`
	RefreshJti_2 pgtype.UUID        `json:"refresh_jti_2"`
}

func (q *Queries) RotateSessionRefresh(ctx context.Context, arg RotateSessionRefreshParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSessionRefresh,
		arg.RefreshJti,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.RefreshJti_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
